# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config', 'config'),
        ('plugins', 'plugins'),
        ('utils', 'utils'),
        ('src', 'src'),
        ('docs', 'docs'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'src.main_window',
        'src.plugin_manager',
        'src.icon_generator',
        'src.animations',
        'src.draggable_tab_widget',
        'src.draggable_toolbar',
        'src.log_viewer',
        'config.preferences',
        'src.signal_manager',
        'src.theme',
        'src.base_plugin',
        'src.plugin_ui_helper',
        'src.ico_converter_util',
        'utils.ToolKey',
        'utils.LogUtils',
        'utils.PDFUtil',
        'plugins.calculator',
        'plugins.image_merger',
        'plugins.sample_text_viewer',
        'plugins.todo_list',
        'plugins.ico_converter',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MTL_UTIL',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)